// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRjHHZloeJoNF5ueAXsT6lLaKZqneLrk',
    appId: '1:769139300588:web:2d12cd4d80f8106be0adc9',
    messagingSenderId: '769139300588',
    projectId: 'finance-master-pro-78d25',
    authDomain: 'finance-master-pro-78d25.firebaseapp.com',
    storageBucket: 'finance-master-pro-78d25.appspot.com',
    measurementId: 'G-YX700CM73S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFV2sVoR_vHdZJlfHayFWzwqkzpGcJbVc',
    appId: '1:769139300588:android:09e3a392f9818132e0adc9',
    messagingSenderId: '769139300588',
    projectId: 'finance-master-pro-78d25',
    storageBucket: 'finance-master-pro-78d25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxXT2UxCqWiA1lULKyy9nfGFHE8DK_t3k',
    appId: '1:769139300588:ios:6898064769f1100ae0adc9',
    messagingSenderId: '769139300588',
    projectId: 'finance-master-pro-78d25',
    storageBucket: 'finance-master-pro-78d25.appspot.com',
    iosBundleId: 'com.example.financeMasterPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxXT2UxCqWiA1lULKyy9nfGFHE8DK_t3k',
    appId: '1:769139300588:ios:b6ebdd26d66d8b19e0adc9',
    messagingSenderId: '769139300588',
    projectId: 'finance-master-pro-78d25',
    storageBucket: 'finance-master-pro-78d25.appspot.com',
    iosBundleId: 'com.example.financeMasterPro.RunnerTests',
  );
}
