  @ -1,95 +1,102 @@
  name: build_upload_notify

  on:
    push:
      branches:
        - main
        - edit

  jobs:
    build_upload_notify:
      name: Build, Upload, and Notify
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set up Java
          uses: actions/setup-java@v1
          with:
            java-version: '12.x'

        - name: Set up Flutter
          uses: subosito/flutter-action@v1
          with:
            channel: 'stable'

        - name: Get Branch Name
          id: branch
          run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

        - name: Get Today's Date
          id: date
          run: echo "date=$(date +'%d%m%y')" >> $GITHUB_OUTPUT

        - name: Read Current Version
          id: read_version
          run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

        - name: Increment Version
          id: increment_version
          run: |
            current_version="${{ steps.read_version.outputs.version }}"
            IFS='.' read -r -a version_parts <<< "$current_version"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            
            if [ $minor -eq 9 ]; then
              major=$((major + 1))
              minor=0
            else
              minor=$((minor + 1))
            fi
            
            new_version="$major.$minor"
            echo "new_version=$new_version" >> $GITHUB_OUTPUT
            echo $new_version > version.txt

        - name: Get Folder Id by Condition
          id: folder_id
          run: echo "value=${{ secrets.DRIVEFOLDERID }}" >> $GITHUB_OUTPUT

        - name: Install Flutter Dependencies
          run: flutter pub get

        - name: Build APK
          run: flutter build apk --release

        - name: Build iOS
          run: |
            flutter build ios --no-codesign
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload

        - name: Archive Files
          run: |
            sudo apt-get update
            sudo apt-get install -y zip
            zip -r archive.zip build/app/outputs/apk/release/app-release.apk

        - name: Upload to Google Drive
          uses: adityak74/google-drive-upload-git-action@main
          with:
            credentials: ${{ secrets.CREDENTIALS }}
            filename: "build/app/outputs/apk/release/app-release.apk"
            folderId: ${{ steps.folder_id.outputs.value }}
            name: "Finance Master Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk"
            overwrite: "true"
            mimeType: "application/vnd.android.package-archive"

        - name: Configure Git
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"

        - name: Commit Updated Version
          run: |
            git add version.txt
            git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
            git push origin HEAD:${{ github.ref }}

        - name: Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/release/Finance_Master_Pro,build/ios/iphoneos/app.ipa"
            tag: v1.0.${{ github.run_number }}
            token: ${{ secrets.GH_PAT }}
