name: build_upload_notify

on:
  push:
    branches:
      - main
      - edit

jobs:
  build_upload_notify:
    name: build_upload_notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get Branch Name
        id: branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Get Today Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Get Folder Id by condition
        uses: haya14busa/action-cond@v1
        id: folder_id
        with:
          cond: ${{ steps.branch.outputs.branch == 'edit' }}
          if_true: ${{ secrets.DRIVEFOLDERID }}
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Archive Files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "build/app/outputs/apk/release/app-release.apk"
          folderId: ${{ steps.folder_id.outputs.value }}
          name: ${{ steps.date.outputs.branch }}-${{ steps.branch.outputs.date }}.apk
          overwrite: "true"
          mimeType: "application/vnd.android.package-archive"
