name: build_upload_notify

on:
  push:
    branches:
      - main
      - edit

jobs:
  build_upload_notify:
    name: build_upload_notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get Branch Name
        id: branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Get Today Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Get Folder Id by condition
        uses: haya14busa/action-cond@v1
        id: folder_id
        with:
          cond: ${{ steps.branch.outputs.branch == 'edit' }}
          if_true: ${{ secrets.DRIVEFOLDERID }}
      - run: flutter pub get
      - run: flutter build apk --release
#      - name: Upload APK to Google Drive
#        uses: jakejarvis/google-drive-upload-action@master
#        with:
#          service-account-auth: ${{ secrets.SERVICE_ACCOUNT_AUTH }}
#          file: build/app/outputs/flutter-apk/app-release.apk
#          folder-id: ${{ steps.folder_id.outputs.result }}
#          name: app-release-${{ steps.branch.outputs.branch }}-${{ steps.date.outputs.date }}.apk