name: build_upload_notify

on:
  push:
    branches:
      - release

jobs:
  build_upload_notify:
    name: Build, Upload, and Notify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get Branch Name
        id: branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Get Today's Date
        id: date
        run: echo "date=$(date +'%d%m%y')" >> $GITHUB_OUTPUT

      - name: Read Current Version
        id: read_version
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Increment Version
        id: increment_version
        run: |
          current_version="${{ steps.read_version.outputs.version }}"
          IFS='.' read -r -a version_parts <<< "$current_version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          
          if [ $minor -eq 9 ]; then
            major=$((major + 1))
            minor=0
          else
            minor=$((minor + 1))
          fi
          
          new_version="$major.$minor"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo $new_version > version.txt

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update pubspec.yaml version
        run: python update_pubspec_version.py

      - name: Install Google API Client
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Install requests
        run: pip install requests

      - name: Install slack-sdk
        run: pip install slack-sdk

      - name: Delete Existing Files from Google Drive
        env:
          FOLDER_ID: ${{ secrets.DRIVEFOLDERID }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.CREDENTIALS }}
        run: python delete_drive_files.py

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK File
        run: |
          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/Finance_Master_Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk

      - name: Archive Files
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          zip -r archive.zip build/app/outputs/apk/release/Finance_Master_Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk

      - name: Fetch Latest APK URL
        id: fetch_apk_url
        run: python fetch_latest_apk_url.py
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          DRIVEFOLDERID: ${{ secrets.DRIVEFOLDERID }}

      - name: Upload to Google Drive
        id: upload
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "build/app/outputs/apk/release/Finance_Master_Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk"
          folderId: ${{ secrets.DRIVEFOLDERID }}
          name: "Finance Master Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk"
          overwrite: "true"
          mimeType: "application/vnd.android.package-archive"

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit Updated Version
        run: |
          git add version.txt pubspec.yaml
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
          git push origin HEAD:${{ github.ref }}

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/Finance_Master_Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk,build/ios/iphoneos/app.ipa"
          tag: v${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}
          token: ${{ secrets.GH_PAT }}

      - name: Upload APK to Slack
        run: python upload_to_slack.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          APK_FILE_PATH: build/app/outputs/apk/release/Finance_Master_Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk

      - name: Notify on Slack with APK
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Finance Master Pro
          SLACK_TITLE: "🎉🎉 New Release Available 🎉🎉"
          SLACK_MESSAGE: |
            A new release of Finance Master Pro is available. Version: ${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}
          SLACK_COLOR: good
          SLACK_CHANNEL: "#finance-master-pro"
          SLACK_ICON: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQIdeZ1MahCe2snsur1xczoHnlPx6ENMuJH6UDWWhNYjIfAQyuj"

      - name: Update Firebase Remote Config
        run: python update_firebase_remote_config.py
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          APK_URL: ${{ steps.fetch_apk_url.outputs.apk_url }}

      - name: Upload APK and Send Telegram Message
        run: python send_telegram_message.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          MESSAGE: "A new release of Finance Master Pro is available. Version: ${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}"
          APK_FILE_PATH: build/app/outputs/apk/release/Finance_Master_Pro-${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}.apk



#      - name: Notify on WhatsApp
#        run: python send_whatsapp_message.py
#        env:
#          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
#          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
#          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
#          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
#          MESSAGE: "A new release of Finance Master Pro is available. Version: ${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}"
#
#      - name: Notify on Messenger
#        run: python send_messenger_message.py
#        env:
#          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
#          MESSAGE: "A new release of Finance Master Pro is available. Version: ${{ steps.increment_version.outputs.new_version }}.${{ steps.date.outputs.date }}"
#          USER_ID: ${{ secrets.USER_ID }}

